
drop table public.movie;
drop table public.director;


create table public.director(
                                director_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name varchar(100) NOT NULL UNIQUE,
                                age int CHECK ( age > 10 )
);

create table public.movie (
                              movie_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              director_id int not null REFERENCES public.director(director_id),
                              name varchar(200) NOT NULL,
                              year_of_production int CHECK ( year_of_production>1900 )
);

insert into public.director(name, age) VALUES
                                           ('Quentin Tarantino', 57),
                                           ('Martin Scorsese', 78),
                                           ('Guy Ritchie', 52),
                                           ('Woody Allen', 85),
                                           ('David Lynch', 74),
                                           ('Christopher Nolan', 50);

insert into public.movie (director_id, name, year_of_production) values
                                                                     (1,'Reservoir Dogs',1992),
                                                                     (1,'Pulp Fiction',1994),
                                                                     (1,'The Hateful Eight',2015),
                                                                     (1,'One Upon a Time in Hollywood',2019),
                                                                     (2,'Taxi Driver',1976),
                                                                     (2,'Goodfellas',1990),
                                                                     (2,'The Wolf of Wall Street',2013),
                                                                     (3,'Lock, Stock and Two Smoking Barrels',1998),
                                                                     (3,'Snatch',2000),
                                                                     (4,'Midnight in Paris', 2011),
                                                                     (6,'Inception',2010);


select * from public.director;

select * from public.movie;

insert into movie(director_id, name, year_of_production) VALUES (7, 'sdasd', 2003);

select d.name, m.name from director d left join movie m on d.director_id = m.director_id;

create table citizen (
                         citizen_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                         name varchar(100) NOT NULL ,
                         age int check ( age>0 )
);

create table passport (
                          citizen_id int PRIMARY KEY REFERENCES citizen(citizen_id),
                          passport_number int
);

insert into citizen(name, age) values
                                   ('Bob', 12),
                                   ('Tom', 24),
                                   ('Katy', 39),
                                   ('Alice', 45);

insert into passport (citizen_id, passport_number)
values (1,12345),
       (2,75124),
       (3,91245),
       (4,19259);


select * from citizen;
select * from passport;

insert into passport (citizen_id, passport_number)
values (55,12345);

insert into citizen (name, age)
values ('Joe',1);

select c.name, p.passport_number from citizen c left join passport p on c.citizen_id = p.citizen_id;



create table actor(
                      actor_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                      name varchar(100) not null unique,
                      age int check (age>0)
);



select * from movie;


insert into actor(name, age) VALUES
                                 ('Harvey Keitel', 81),
                                 ('Robert De Niro', 78),
                                 ('Leonardo DiCaprio', 46),
                                 ('Jason Statham', 53),
                                 ('Joe Pesci', 77),
                                 ('Samuel L. Jackson', 72);

select * from actor;

create table actor_movie(
                            actor_id int REFERENCES actor(actor_id),
                            movie_id int REFERENCES movie(movie_id),
                            primary key (actor_id, movie_id)
);


INSERT INTO actor_movie values
                            (1,1),
                            (1,2),
                            (2,5),
                            (2,6),
                            (3,4),
                            (3,7),
                            (3,11),
                            (4,8),
                            (4,9),
                            (5,6),
                            (6,2),
                            (6,3);

select * from actor_movie;

select * from actor where actor_id = 1;
select * from movie where movie_id = 1;

insert into actor_movie values (6,3);

select  a.name, m.name from actor a
    join actor_movie am on a.actor_id = am.actor_id
    join movie m on am.movie_id = m.movie_id;


drop table "order";
drop table people;

create table people(
                       user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                       name varchar(100) not null ,
                       age int
);

create table "order" (
                         order_id int generated by default as identity primary key ,
                         user_id int REFERENCES people(user_id) on delete cascade ,
                         iten_name varchar(100)
);

insert into people (name, age)
values ('Tom',33);

insert into "order"(user_id, iten_name) VALUES (1, 'Iphone');

select * from people;
select * from "order";


delete from people where user_id=1;

